AECPrototype/AECPrototype/Controllers/ProductController.cs
using AECPrototype.Models;
using AECPrototype.Services;
using AECPrototype.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AECPrototype.Controllers
{
    public class ProductController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly ProductService productService;

        public ProductController(UserManager<User> _userManager, SignInManager<User> _signInManager, ProductService _productService)
        {
            userManager = _userManager;
            signInManager = _signInManager;
            productService = _productService;
        }

        [Authorize(Roles = "Farmer")]
        public IActionResult UserProduct()
        {
            return View();
        }

        [Authorize(Roles = "Farmer")]
        public IActionResult AddProduct()
        {
            return View();
        }

        [Authorize(Roles = "Employee")]
        public IActionResult SearchProducts()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Farmer")]
        public async Task<IActionResult> AddProduct(AddProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product
                {
                    Title = model.Title,
                    Category = model.Category,
                    Date = model.Date,
                    UserId = userManager.GetUserId(User)
                };
                await productService.CreateProductAsync(product);

                return RedirectToAction("UserProduct");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Farmer")]
        public async Task<IActionResult> UserProduct(UserProductViewModel model)
        {
            var userId = userManager.GetUserId(User);

            var products = await productService.GetProductsByUserIdAsync(userId);

            var viewModel = products.Select(p => new UserProductViewModel
            {
                ProductId = p.ProductId.ToString(),
                Title = p.Title,
                Category = p.Category,
                Date = p.Date
            }).ToList();

            return View(viewModel);
        }


        [Authorize(Roles = "Employee")]
        [HttpGet]
        public async Task<IActionResult> SearchProducts(FilterProductViewModel model)
        {
            var categories = await productService.GetAllProductCategoriesAsync();

            var farmers = await userManager.GetUsersInRoleAsync("Farmer");

            List<FarmerViewModel> farmerList = new List<FarmerViewModel>();

            if (farmers.Any())
            {
                foreach (var user in farmers)
                {
                    var farmerVM = new FarmerViewModel
                    {
                        FarmerName = user.FirstName + " " + user.LastName,
                        FarmerId = user.Id
                    };
                    farmerList.Add(farmerVM);
                }
            }

            if (farmerList.Count() != 0 && farmerList != null)
            {
                model.Farmers = farmerList;
            }

            if (categories != null)
            {
                model.Categories = categories.ToList();
                return View(model);
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Employee")]
        public async Task<IActionResult> FilterProduct(FilterProductViewModel model)
        {
            if (model.FromDate != null && model.ToDate == null)
            {
                ModelState.AddModelError("ToDate", "Select a date.");
            }
            else if (model.FromDate == null && model.ToDate != null)
            {
                ModelState.AddModelError("FromDate", "Select a date.");
            }
            else
            {
                var filteredProducts = await productService.GetFilteredProductsAsync(model);
                if (filteredProducts.Count != 0)
                {
                    foreach (var product in filteredProducts)
                    {
                        var productVM = new ProductViewModel
                        {
                            Id = product.ProductId.ToString(),
                            Title = product.Title,
                            Category = product.Category,
                            FarmerName = product.User.FirstName + " " + product.User.LastName,
                            Date = product.Date,
                        };
                        model.Products.Add(productVM);
                    }
                }
            }

            var categories = await productService.GetAllProductCategoriesAsync();

            var farmers = await userManager.GetUsersInRoleAsync("Farmer");

            List<FarmerViewModel> farmerList = new List<FarmerViewModel>();

            if (farmers.Any())
            {
                foreach (var user in farmers)
                {
                    var farmerVM = new FarmerViewModel
                    {
                        FarmerName = user.FirstName + " " + user.LastName,
                        FarmerId = user.Id
                    };
                    farmerList.Add(farmerVM);
                }
            }

            if (farmerList.Count() != 0 && farmerList != null)
            {
                model.Farmers = farmerList;
            }

            if (categories != null)
            {
                model.Categories = categories.ToList();
            }

            return View("SearchProducts", model);
        }

    }
}

AECPrototype/AECPrototype/Controllers/UserController.cs
using AECPrototype.Models;
using AECPrototype.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AECPrototype.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> logger;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;

        public UserController(ILogger<UserController> _logger, UserManager<User> _userManager, SignInManager<User> _signInManager)
        {
            logger = _logger;
            userManager = _userManager;
            signInManager = _signInManager;
        }

        public IActionResult UnauthorizedAccess()
        {
            return View();
        }

        [Authorize(Roles = "Employee")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.SuccessMessage = TempData["SuccessMessage"] as string;
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Employee")]
        public async Task<IActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    UserName = model.Email
                };

                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user, model.Role);

                    return RedirectToAction("Create");
                }

                else
                {
                    foreach (var error in result.Errors.Where(e => e.Code != "DuplicateUserName"))
                    {
                        if (error == result.Errors.FirstOrDefault(e => e.Code == "DuplicateEmail"))
                        {
                            ModelState.AddModelError("Email", "This email is already taken.");
                        }
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Profile");
                }
                else
                {
                    ViewBag.FailedMessage = "Invalid email or password.";
                    return View(model);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Farmer, Employee")]
        public async Task<IActionResult> Profile()
        {
            var user = await userManager.GetUserAsync(User);

            var role = (await userManager.GetRolesAsync(user)).FirstOrDefault();

            UserViewModel model = new UserViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Role = role
            };

            ViewBag.SuccessMessage = TempData["SuccessMessage"] as string;

            return View(model);
        }

    }
}

AECPrototype/AECPrototype/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> signInManager;

@{
	var signedIn = signInManager.IsSignedIn(User);
}

@if (!signedIn)
{
	<div class="rightbar">
		<a asp-action="Login" asp-controller="User" class="button-partial">Login</a>
	</div>
}
else
{
	<div class="rightbar">
		<form asp-action="Logout" asp-controller="User" method="post">
			<button class="button-partial" type="submit">Logout</button>
		</form>
	</div>
}

<div class="sidebar">
	<div class="logo-menu">
		<h2 class="logo">Menu</h2>
		<i class="bx bx-menu toggle-btn"></i>
	</div>

	<ul class="list">
		<li class="list-item">
			<a class="nav-link" asp-controller="Home" asp-action="Index">
				<i class="bx bx-home"></i>
				<span class="link-name" style="--i:1;">Home</span>
			</a>
		</li>

		@if (signedIn)
		{
			<li class="list-item">
				<a class="nav-link" asp-controller="User" asp-action="Profile">
					<i class='bx bx-user'></i>
					<span class="link-name" style="--i:2;">Profile</span>
				</a>
			</li>


			<li class="list-item">
				<a class="nav-link" asp-controller="Product" asp-action="SearchProducts">
					<i class='bx bx-filter-alt'></i>
					<span class="link-name" style="--i:3;">Filter Products</span>
				</a>
			</li>

			<li class="list-item">
				<a class="nav-link" asp-controller="User" asp-action="Create">
					<i class='bx bx-user-plus'></i>
					<span class="link-name" style="--i:4;">Register User</span>
				</a>
			</li>

			<li class="list-item">
				<a class="nav-link" asp-controller="Product" asp-action="AddProduct">
					<i class='bx bx-plus'></i>
					<span class="link-name" style="--i:5;">Add Product</span>
				</a>
			</li>

			<li class="list-item">
				<a class="nav-link" asp-controller="Product" asp-action="UserProduct">
					<i class='bx bx-leaf'></i>
					<span class="link-name" style="--i:6;">Your Products</span>
				</a>
			</li>
		}

	</ul>
</div>

AECPrototype/AECPrototype/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AECPrototype</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <partial name="LoginPartial" />

        <main role="main">
            @RenderBody()
        </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>